language: python

python:
  - '2.7'

install:
  - pip install coveralls
  - pip install -r requirements.txt
  - sudo mkdir -p /etc/aclhound ~/.aclhound/
  - sudo chown travis /etc/aclhound ~/.aclhound/
  - sudo cp tests/data/aclhound.conf /etc/aclhound
  - sudo cp tests/data/client.conf ~/.aclhound/client.conf
  - echo "machine concepts-ict.mu.meerval.net login ${IOS_DEPLOY_USERNAME} password ${IOS_DEPLOY_PASSWORD} account ${IOS_DEPLOY_PASSWORD}" > ~/.netrc
  - chmod 0600 ~/.netrc
  - python setup.py install

script:
  - python setup.py nosetests

after_success:
  - coveralls
  - rm ~/.netrc

env:
  global:
  - secure: "UwknUnSACIea1Lp20daKB9Dei6AZWKr0DIzZYdpVOoJk9vJ2PlOReofaEm7SBpCfH0RFmxhnei3ykANQeiekHCb0voob3Aq1XNiF6dwPJ+O0StmuYMzrOQYMGl9To9CzfhWsLjwvXqSgd948DdmJa1KY0dag/EhbuuKnmkwDKGU="
  - secure: "cCshr1SyGg99y1h/IWRuVImIASaKhm+sQUmF7WBwpwwBk2L6i2nRbW/GqIN2tLKmmAo0E5IiJUh31ouG3g2knG/K0TG7Em1A7h1+1kD8sXqLo9b9Ow4vfXt6PLDwMv2AR5DO7m4xSGMithtlllKfckhvFOhxkLVSPKWQ1AEQvmE="
