language: python
sudo: required
python:
- '2.7'
install:
- pip install coveralls
- pip install -r requirements.txt
- sudo mkdir -p /etc/aclhound ~/.aclhound/
- sudo chown travis /etc/aclhound ~/.aclhound/
- sudo cp tests/data/aclhound.conf /etc/aclhound
- sudo cp tests/data/client.conf ~/.aclhound/client.conf
- echo "194.50.70.111 arista.eby" | sudo tee -a /etc/hosts
- echo "machine steffann.mu.meerval.net login ${IOS_DEPLOY_USERNAME} password ${IOS_DEPLOY_PASSWORD} account ${IOS_DEPLOY_PASSWORD}" > ~/.netrc
- echo "machine arista.eby login ${ARISTA_DEPLOY_USERNAME} password ${ARISTA_DEPLOY_PASSWORD} account ${ARISTA_DEPLOY_PASSWORD}" >> ~/.netrc
- chmod 0600 ~/.netrc
- python setup.py install
script:
- python setup.py nosetests
after_success:
- coveralls
- rm ~/.netrc
env:
  global:
  - secure: "f4bPLx4QCcX3+Ucyh/mwUzPRnnHRL14jTOXNc1vAd7iKd05iOmE/B3ZTHKeKnk26AIs7qOrsACDy49Pi/HupMzqpuebMtbEMUZGYSowSI/7TbJ2axNdbTKB+2hlPCQggYqxL001UztvaFffrQM2GFhHQcrprbv9RsNGistpquKI="
  - secure: "eg1WwwWn+ENn3ShkfCMbCwhSAKPs5bTJNRKIJqy75AFX0CRZwT3FgzbtkOlPGxP9KN5PDzj2KwGOYV1qAQlk203/xG2XBvvXB8Zr5MBtWSwYsDPQKcu7JXG8grrdHdgv7ncjwb9qUdgMJ+pzEGnj4lS3/n8lLPw2A5y7WherQbU="
  - secure: "CaPGCln0m1Tfs1sZX7c9u2fLV7/5jaC5Z4kubfhs1Q8qjanF8lBNl9NLU5ABCbpkd1wE514I8l0qHAsbmEz3WSjekrTy+EeiRL58yWepCqmYcVZel8Ysw0b10OQsBEmU+EBiDpVDx/sa8R26bdHNi+WTn+q0E+QPzGBbTCf3aBc="
  - secure: "dyLP72d+VY+s1ZTtyaTpdRgUbMO9CuWHcAQcsjekZxMWTWu+UmZ6jAUOhRat3jEBtPK1NvHI+kkqNr3AkjHD6yeULaPbkp5x4NSFAwJhcerzxzvy8pfJHqfkBUmw+eL8dQIIkHhTwWbwMQEyUj8Dt88JlHvwVmPxkQVZOcTXzZo="
