language: python

python:
  - "pypy"
  - "2.6"
  - "2.7"

install:
  - pip install --use-mirrors coveralls 
  - python setup.py install

script:
  - python setup.py nosetests

after_success:
  - coveralls
