language: python

python:
  - '2.7'

install:
  - pip install coveralls
  - pip install -r requirements.txt
  - sudo mkdir -p /etc/aclhound ~/.aclhound/
  - sudo chown travis /etc/aclhound ~/.aclhound/
  - sudo cp tests/data/aclhound.conf /etc/aclhound
  - sudo cp tests/data/client.conf ~/.aclhound/client.conf
  - echo "machine concepts-ict.mu.meerval.net login ${IOS_DEPLOY_USERNAME} password ${IOS_DEPLOY_PASSWORD} account ${IOS_DEPLOY_PASSWORD}" > ~/.netrc
  - chmod 0600 ~/.netrc
  - python setup.py install

script:
  - python setup.py nosetests

after_success:
  - coveralls
  - rm ~/.netrc

env:
  global:
  - secure: Cj82DF4mWVjgekBRFnFmOnj1ySGDIGFsXtTZgg4FG5OoVCpxc+/cTCJymJRb/6frgiFNu404pWuNowluLLpBRssFpkGB5G3eK8Vvzlw2YH/p89VRFhxYZGnci0Q8olfTnVuTSKOrQxuL7PHXf+gk+SPPtXt2UH+W6Ky//0BzGQQ=
  - secure: IZh//rLNAFGAOvAzjSTvv38AFeRZVs5e6N4umQZPG/l5u/Gzidbw1EXXvhz9S1XfYqoqw5hCUJQ/GOoe5Hx0g37ef4Cv58LrftRgETcH3Q2M7DYp2wIu3GpzRpQ0oH7DcRY2ToJlYefc3tvOzQg+nmn6uLQfTNNG3PNMjtGUBQA=
