language: python

python:
  - "pypy"
  - "2.7"

install:
  - pip install coveralls
  - sudo apt-get install jenkins
  - python setup.py install

script:
  - python setup.py nosetests

after_success:
  - coveralls
