language: python

python:
  - "2.7"

install:
  - pip install coveralls
  - sudo apt-get install jenkins
  - sudo python setup.py install
  - sudo mv /etc/aclhound/aclhound.conf.dist /etc/aclhound/aclhound.conf

script:
  - python setup.py nosetests

after_success:
  - coveralls
